// Temporary sample data — the backend /equipment module isn't implemented yet.
// Swap MOCK_EQUIPMENT for the real fetch in context.tsx once it is; the shape
// already matches the Equipment type the rest of this feature consumes.
import type { Equipment, MaintenanceLogEntry } from "./types";

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: "mock-1",
    equipmentId: "RR-04",
    name: "Rotary Rig",
    status: "ACTIVE",
    year: 2021,
    serialNumber: "SN-88213",
    model: "Bauer BG 28 H",
    manufacturer: "Bauer",
    equipmentCode: "RR-04",
    fuelLevelPercent: 78,
    engineHours: 1240,
    idleHours: 42,
    location: "Sky Tower A – Zone 2",
    assignedTo: "Zone 2 Crew",
  },
  {
    id: "mock-2",
    equipmentId: "AR-02",
    name: "Anchor Rig",
    status: "IDLE",
    maintenanceDueInDays: 2,
    year: 2019,
    serialNumber: "SN-40217",
    model: "Casagrande C6",
    manufacturer: "Casagrande",
    equipmentCode: "AR-02",
    fuelLevelPercent: 45,
    engineHours: 3890,
    idleHours: 112,
    location: "Yard B – Storage",
    assignedTo: null,
  },
  {
    id: "mock-3",
    equipmentId: "AC-03",
    name: "Air Compressor",
    status: "ACTIVE",
    year: 2022,
    serialNumber: "SN-77490",
    model: "Atlas Copco XAS 185",
    manufacturer: "Atlas Copco",
    equipmentCode: "AC-03",
    fuelLevelPercent: 82,
    engineHours: 640,
    idleHours: 15,
    location: "Metro Line – Sec 4",
    assignedTo: "Zone 4 Crew",
  },
  {
    id: "mock-4",
    equipmentId: "EX-15",
    name: "Excavator",
    status: "BREAKDOWN",
    year: 2018,
    serialNumber: "SN-15590",
    model: "CAT 336",
    manufacturer: "Caterpillar",
    equipmentCode: "EX-15",
    fuelLevelPercent: 12,
    engineHours: 4120,
    idleHours: 89,
    location: "Metro Line – Sec 4",
    assignedTo: "Zone 4 Crew",
  },
  {
    id: "mock-5",
    equipmentId: "CR-06",
    name: "Crane",
    status: "ACTIVE",
    year: 2020,
    serialNumber: "SN-62810",
    model: "Liebherr LTM 1090",
    manufacturer: "Liebherr",
    equipmentCode: "CR-06",
    fuelLevelPercent: 65,
    engineHours: 2100,
    idleHours: 60,
    location: "Sky Tower B",
    assignedTo: "Tower Crew",
  },
  {
    id: "mock-6",
    equipmentId: "GN-07",
    name: "Generator",
    status: "IDLE",
    year: 2017,
    serialNumber: "SN-33108",
    model: "Caterpillar XQ230",
    manufacturer: "Caterpillar",
    equipmentCode: "GN-07",
    fuelLevelPercent: 30,
    engineHours: 980,
    idleHours: 340,
    location: "Yard A – Storage",
    assignedTo: null,
  },
  {
    id: "mock-7",
    equipmentId: "GP-08",
    name: "Grout Pump",
    status: "MAINTENANCE",
    year: 2019,
    serialNumber: "SN-90056",
    model: "Putzmeister BSA 1005",
    manufacturer: "Putzmeister",
    equipmentCode: "GP-08",
    fuelLevelPercent: 55,
    engineHours: 1520,
    idleHours: 75,
    location: "Workshop",
    assignedTo: null,
  },
];

export const MOCK_MAINTENANCE_LOG: MaintenanceLogEntry[] = [
  {
    id: "log-1",
    equipmentId: "EX-15",
    issue: "Hydraulic Leak",
    reportedAt: "Oct 24, 09:30 AM",
    status: "Open",
  },
  {
    id: "log-2",
    equipmentId: "AR-02",
    issue: "Filter Change Due",
    reportedAt: "Oct 23, 14:15 PM",
    status: "Scheduled",
  },
  {
    id: "log-3",
    equipmentId: "RR-04",
    issue: "Track Tension Adj.",
    reportedAt: "Oct 21, 11:00 AM",
    status: "Resolved",
  },
  {
    id: "log-4",
    equipmentId: "GP-08",
    issue: "Routine Insp.",
    reportedAt: "Oct 20, 08:00 AM",
    status: "Resolved",
  },
  {
    id: "log-5",
    equipmentId: "GN-07",
    issue: "Low Coolant Level",
    reportedAt: "Oct 19, 16:40 PM",
    status: "Open",
  },
  {
    id: "log-6",
    equipmentId: "CR-06",
    issue: "Cable Inspection",
    reportedAt: "Oct 18, 10:20 AM",
    status: "Scheduled",
  },
  {
    id: "log-7",
    equipmentId: "AC-03",
    issue: "Air Filter Replaced",
    reportedAt: "Oct 16, 09:00 AM",
    status: "Resolved",
  },
  {
    id: "log-8",
    equipmentId: "EX-15",
    issue: "Undercarriage Wear Check",
    reportedAt: "Oct 14, 13:10 PM",
    status: "Resolved",
  },
];
